pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    parameters {
        choice (
        choices: ['start', 'destroy'],
        description: '',
        name: 'action'
        )
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage('Terraform init') {
            steps {
                dir('task_10') {
                    sh 'terraform init'
                }
            }
        }

        stage('Deploy infra') {
            when {
                expression { params.action == 'start'}
            }
            steps {
                
                dir('task_10') {
                    withAWS(credentials:'cloud-tech', region:'us-east-1') {
                        sh 'terraform plan'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Destroy infra') {
            when {
                expression { params.action == 'destroy'}
            }
            steps {
                
                dir('task_10') {
                    withAWS(credentials:'cloud-tech', region:'us-east-1') {
                        sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}